### ISSUE TITLE
Upgrade to pandas version 2.1.0

### ISSUE THREAD

**Issue by tfenesel** [SignalOceanSdk/SignalSDK#285]
Hello,

We just recently bought an API license only to realise the Python SDK is only compatible with pandas < 2.

We're using pandas 2.0.2 so this is a bit of a bummer. There's so much within the SDK we would love to take advantage of but won't be able to until this upgrade is made.

**Comment by ktsitsikas-signal** [comment]
fixed in version 8.0.0
